import {
  KeyRound,
  QrCode,
  ScanLine,
  Building2,
  User,
  Users,
  CalendarClock,
  History,
  Bell,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  Search,
  Plus,
  Settings,
  LogOut,
} from "lucide-react-native";

export const AppIcons = {
  key: KeyRound,
  qr: QrCode,
  scan: ScanLine,
  property: Building2,
  user: User,
  users: Users,
  booking: CalendarClock,
  history: History,
  notification: Bell,
  available: CheckCircle2,
  warning: AlertTriangle,
  unavailable: XCircle,
  search: Search,
  add: Plus,
  settings: Settings,
  logout: LogOut,
};
